### ISSUE TITLE
EMA算子实现

### ISSUE THREAD

**Issue by SniperUsopp** [Menooker/KunQuant#13]
Hi，我在尝试实现EMA算子时遇到了一些问题。想请教一下。

我看在KunQuant的封装中，循环是通过IterValue实现。而IterValue需要传入一个ForeachBackWindow作为参数，ForeachBackWindow是需要设置一个windowsize值。而EMA算子并不涉及窗口大小。请问这种情况该怎么实现循环呢。

**Comment by Menooker** [comment]
你其实需要StatefulOp。KunQaunt生成的程序基本上就是
```c++
for(int i=0;i<num_time;i++) {
   ...
}
```

的循环，而EMA需要记录上一次循环i的对应的状态。我在CodegenCpp里面会对这样的Op特殊处理（目前只有FastWindowedSum），在这个主循环外面放置一个状态：

```c++
FastWindowedSum sum;
for(int i=0;i<num_time;i++) {
   ...
   auto cur_sum = sum.step(window_data, cur_data, i);
}
```

`FastWindowedSum` 实现在了`Ops.hpp`，可以参考一下里面放了什么状态。

我刚刚提交了https://github.com/Menooker/KunQuant/pull/14 ，添加了EMA。实现上和`FastWindowedSum` 差不多。你可以参考一下。这个Op目前和Pandas `pd.DataFrame(inp).ewm(span=5, adjust=False).mean()`的行为保持一致。

> 我看在KunQuant的封装中，循环是通过IterValue实现。而IterValue需要传入一个ForeachBackWindow作为参数，ForeachBackWindow是需要设置一个windowsize值。而EMA算子并不涉及窗口大小。请问这种情况该怎么实现循环呢。

`IterValue`和`ForeachBackWindow` 可能不是你想要的。这个主要是用来在主循环内部写循环的：

```c++
for(int i=0;i<num_time;i++) {
   ...
   for(int w=0;w<window;w++) {
     ....
   }
}
```

主要是用来实现在backwindow上reduce的操作，比如windowedMin、stddev之类

**Comment by Menooker** [comment]
#14 已经合并
