### ISSUE TITLE
请问Alpha158中的算子RSQR、Resi以及Quantile是无法计算吗

### ISSUE THREAD

**Issue by muhoushaonian** [Menooker/KunQuant#15]

**Comment by Menooker** [comment]
是的，暂时还不支持，因为我自己没有用到（滑稽
如果你有这个需求的话，我可以有空的时候加一下。我到时候可能通过PR的方式进行代码更新，如果你有时间也可以帮忙review一下~

**Comment by muhoushaonian** [comment]
哥我有这个需求，如果哥有空更新一下就最好了hhh(我也会试着自己写一下
PS：我对了一下alpha158的因子计算，有一个有问题
IMIXD：fields += [(TsArgMax(self.high, d)-TsArgMax(self.low, d))/d for d in windows]
应该改为
IMIXD：fields += [(TsArgMax(self.high, d)-TsArgMin(self.low, d))/d for d in windows]

**Comment by Menooker** [comment]
> 哥我有这个需求，如果哥有空更新一下就最好了hhh(我也会试着自己写一下 PS：我对了一下alpha158的因子计算，有一个有问题 IMIXD：fields += [(TsArgMax(self.high, d)-TsArgMax(self.low, d))/d for d in windows] 应该改为 IMIXD：fields += [(TsArgMax(self.high, d)-TsArgMin(self.low, d))/d for d in windows]

好的，感谢！我到时候改一下。另外我有两个问题请教：
 * rsquare 等算子qlib内有没有明确的数学定义呢？
 * qlib的alpha158有没有pandas实现？我实现的alpha158暂时没有正确性检查（alpha101有基于pandas的检查）。我不想引入qlib这么大的依赖来跑测试，你知道有什么办法吗？

**Comment by muhoushaonian** [comment]
- 第一个问题是一个非常有意思的问题，我之前用C#转译过python的一些底层运算库，得去看他们的线性回归这种算法具体怎么实现的（据我所知和使用的python第三方包也有关系）例如scipy的线性回归应该是基于最小二乘，这里可能确实是比较费工夫
- 第二个我是将哥你的测试函数改了下，改成先生成csv再dump到bin再用qlib的DataHandler生成对应的因子矩阵，我翻了qlib的底层代码好像是不行，没法直接将OLHC的原始矩阵转成Alpha158因子矩阵，我对了哥你生成的结果和qlib的结果，在单精度浮点上面是全部可以对的上的

**Comment by Menooker** [comment]
> * 第一个问题是一个非常有意思的问题，我之前用C#转译过python的一些底层运算库，得去看他们的线性回归这种算法具体怎么实现的（据我所知和使用的python第三方包也有关系）例如scipy的线性回归应该是基于最小二乘，这里可能确实是比较费工夫

我主要是怕数学定义上会有什么争议吗？例如有没有bias的stddev之类（n-1还是n）。如果数学公式错了，那么就会和qlib比有正确性问题。如果有公认的数学定义那就ok

> * 第二个我是将哥你的测试函数改了下，改成先生成csv再dump到bin再用qlib的DataHandler生成对应的因子矩阵，我翻了qlib的底层代码好像是不行，没法直接将OLHC的原始矩阵转成Alpha158因子矩阵，我对了哥你生成的结果和qlib的结果，在单精度浮点上面是全部可以对的上的

感谢帮忙测试！有兴趣的话可以共享一下你的测试代码和方法嘛？我对qlib不是很熟悉。我之后可以试试看基于你的代码让kunquant能自动测试alpha158，那就最好了。

**Comment by muhoushaonian** [comment]
- qlib中没有提供公式，他是直接调用的python包我猜测，这里确实存在可能数学公式不统一的问题
- 核心的测试代码如下，test.yaml就用qlib的benchmark里面linear yaml就好，最后prepare出来的就是dataframe格式的，我后买你是导出成csv看的，应该也可以做自动对齐

```
def get_alpha158(df):
    stock=Alphas(df)
    num_stock = stock.close.shape[1]
    num_time  = stock.close.shape[0]
    watch_list = []
    for i in range(1, num_stock+1):
        code = f"a{i:03d}"
        watch_list.append(code)
    #watch_list = ["a001", "a002", "a003", "a004", "a005", "a006", "a007", "a008"]
    os.makedirs("/home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/testcsv",exist_ok=True)
    for tmp in watch_list:
        df = pd.DataFrame(columns=["symbol", "date", "close", "open", "high", "low", "vwap", "volume"])
        #df.columns = ["symbol", "date", "close", "open", "high", "low", "vwap", "volume"]
        df["symbol"] = [tmp] * num_time
        df["date"]   = pd.date_range(start="2019-06-01", periods=num_time)
        df["close"]  = stock.close[watch_list.index(tmp)]
        df["open"]  = stock.open[watch_list.index(tmp)]
        df["high"]  = stock.high[watch_list.index(tmp)]
        df["low"]  = stock.low[watch_list.index(tmp)]
        df["vwap"]  = stock.vwap[watch_list.index(tmp)]
        df["volume"]  = stock.volume[watch_list.index(tmp)]
        df.to_csv(f"/home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/testcsv/{tmp}.csv")
    command = "python /home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/dump_bin.py dump_all --csv_path  /home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/testcsv --qlib_dir /home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/testqlib --include_fields open,close,high,low,volume,vwap,factor --symbol_field_name symbol --date_field_name date"
    os.system(command)  
    provider_uri = "/home/jrcxbtrain/pzy/accelerate_cache/kun-quant_new/tests/KunTestUtil/testqlib"
    qlib.init(provider_uri = provider_uri)
    config_file = "test.yaml"
    with open(config_file) as f:
        config = yaml.safe_load(f)
    dataset = init_instance_by_config(config["task"]["dataset"])
    train = dataset.prepare("train")
    print(1)
```

**Comment by Menooker** [comment]
感谢！我到时候试一下！

**Comment by muhoushaonian** [comment]
感谢~ 哥太强了
