### ISSUE TITLE
_mm256_***_epi64 wat not declared in this scope

### ISSUE THREAD

**Issue by muhoushaonian** [Menooker/KunQuant#17]
我run新版本的代码的时候，貌似s64x4.hpp与f64x4会报错
主要问题在于_mm256_***_epi64 wat not declared in this scope
应该是我服务器AVX的指令集不支持，这个有比较好的解决办法吗？(直接用AVX 32位相关的指令重写吗
我看了下好像这两个C++文件主要是服务fast_cast类的

**Comment by Menooker** [comment]
具体是哪几个not declared呢？知道才能排除错误哈~

**Comment by muhoushaonian** [comment]
我在cmake的时候 _mm256_mullo_epi64  _mm256_max_epi64  _mm256_min_epi64  _mm256_abs_epi64这四个是not declared，看了下指令集应该是支持avx2指令集的

**Comment by muhoushaonian** [comment]
补充：我拿32位的指令集重写这四个函数以后，在build alpha158.cpp的时候最后会报错，报错来于Ops.hpp:  ReduceArgMax() ReduceArgMin() WindowedLinearRegression FastWindowedSum ReduceMin，报错信息是conversion from "float/int" to non-scalar type，不知道和我重写是不是有关系

**Comment by muhoushaonian** [comment]
补充：这个报错可以通过自己手动做类型转换解决，但是不知道这么改写是否会对正确性有影响

**Comment by Menooker** [comment]
看来你的CPU是支持AVX512但是不支持AVX512VL 和AVX512DQ啊。我手头上没有AVX512的机器，没法测试到这种情况。 我提交了这个PR https://github.com/Menooker/KunQuant/pull/18 。能不能帮忙切换到fix_i64 这个分支上试试能不能解决这个问题？

**Comment by muhoushaonian** [comment]
我做了初步测试，_mm256_***_epi64 wat not declared in this scope不会出现，但是后面在build具体的Alpha158.cpp的时候，仍然会出现类型转换的报错，例如：
error: conversion from 'double' to non-scalar type 'kun::ops::ReduceArgMax<double,4>::simd_t {aka kun_simd::vec<double,4>}' 
这类问题出现在包括ReduceArgMax WindowedLinearRegression()等算子的构建中，根据我的经验可以去代码报错的赋值地方给做一个类型转换

**Comment by Menooker** [comment]
你可以发一下具体错误log吗？最好可以把一两个错误位置的Alpha158.cpp代码发一下？我这边没法复现你的问题。还有可以先试试看删除build目录后，重新cmake 重新build试试看，有可能是老的代码没有删除导致的

**Comment by Menooker** [comment]
还有编译器的版本也发一下可以吗

**Comment by muhoushaonian** [comment]
![1](https://github.com/Menooker/KunQuant/assets/32610114/1f8835c6-023f-4d3d-b2fc-dd5f22f863e8)
![2](https://github.com/Menooker/KunQuant/assets/32610114/c91be5dc-e5ad-4b57-9cf3-d947d7e0c549)
我截图了一部分log信息
版本信息：cmake version 3.29.0-rc3  gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

**Comment by Menooker** [comment]
> 补充：我拿32位的指令集重写这四个函数以后，在build alpha158.cpp的时候最后会报错，报错来于Ops.hpp: ReduceArgMax() ReduceArgMin() WindowedLinearRegression FastWindowedSum ReduceMin，报错信息是conversion from "float/int" to non-scalar type，不知道和我重写是不是有关系

你有没有把你的修改回退掉呢？ git diff应该看到空的结果。我切换到gcc 8.3.1没法复现你的问题

**Comment by muhoushaonian** [comment]
I got the reason. 
在cmake ..的时候gcc的version是正常的8.3.*，但是g++这边可能是linux自带源使用的g++的version是4.8.5的版本，我显示指定g++的编译版本以后这个问题就可以解决

**Comment by Menooker** [comment]
所以那个PR可以解决你的问题了吧？

**Comment by muhoushaonian** [comment]
可以的，我关掉这个issues，谢谢哥

**Comment by Menooker** [comment]
老哥我再问一下，你一开始遇到问题的时候，是在尝试启用avx512指令集吗？是不是通过-mavx512f强制开启的avx512？

我刚刚合入了对于avx512的完整支持，建议可以尝试一下！请参考项目最新的readme

**Comment by muhoushaonian** [comment]
是的，我在cmakelist.txt里面强制开启avx512，但是这样会报错，我测试了最新的main branch没有问题

**Comment by Menooker** [comment]
> 是的，我在cmakelist.txt里面强制开启avx512，但是这样会报错，我测试了最新的main branch没有问题


hhhh, 是不是强制开启AVX512没有看到性能提升？上周版本的KunQuant不支持生成AVX512指令，所以就算强制开启avx512应该也没啥性能提升，因为生成的代码没有用到512bit的向量。
我昨天刚刚添加了AVX512的完整支持，你可以通过cmake `-DKUN_AVX512=ON` 开启，另外需要重新生成Alpha158等project的代码（可以rm build目录然后重新cmake）。此外这个issue #17 的问题其实不在于你的CPU有没有AVX512DQ，而是你的编译选项有没有开启-mavx512dq。在main branch上，你可以通过cmake `-DKUN_AVX512DQ=ON -DKUN_AVX512VL=ON`开启这两个选项，得到最好的性能。需要先看一下lscpu确认你的CPU支不支持这两个指令集。
其他的请参考main branch的readme的AVX512章节！

**Comment by muhoushaonian** [comment]
好的，谢谢老哥，我去试试~(ps：一个小问题，这边是没法生成未来收益率这种算子吗？我看了下BackRef好像是只能取过去的？

**Comment by muhoushaonian** [comment]
对的，未来收益率只能做label hhh(看来只能这样了hhh

**Comment by Menooker** [comment]
> 对的，未来收益率只能做label hhh(看来只能这样了hhh

嗯嗯可以用kunquant生成close/Backref(close,1) 然后结果shift一下，哈哈

**Comment by muhoushaonian** [comment]
哈哈哈哈哈我现在就是这么弄的，谢谢老哥



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 16, 2024 18:00 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Menooker/KunQuant] _mm256_***_epi64 wat not declared in thisscope (Issue #17)




  
对的，未来收益率只能做label hhh(看来只能这样了hhh
  
嗯嗯可以用kunquant生成close/Backref(close,1) 然后结果shift一下，哈哈
