### ISSUE TITLE
Alpha158分钟线因子计算中IMAX IMIN计算问题

### ISSUE THREAD

**Issue by wangzaimilk123** [Menooker/KunQuant#19]
老哥您好，我在复现使用您的项目时，发现IMAX IMIN和qlib无法对齐，检查计算逻辑问题应该是出在high low相同的时候，框架和qlib的处理逻辑不同，举例如下：
若当前的high为0.6968635916291558，前五个bar的high为
[ 0.6898481863442985, 0.6992020600574415, 0.6992020600574417, 0.6968635916291558, 0.6968635916291558 ]
qlib计算的结果是0.8，但是本框架的计算结果是1，因为qlib是用第四个数据的index除5

**Comment by Menooker** [comment]
谢谢你发现问题，我会看一下的。所以确认一下，主要问题在于对于相同的数据，我的argmax返回最大的index，qlib返回最小的？

**Comment by Menooker** [comment]
确认了一下，qlib使用的是pandas的argmax，返回的是最小的index
https://github.com/microsoft/qlib/blob/c9ed050ef034fe6519c14b59f3d207abcb693282/qlib/data/ops.py#L971
https://pandas.pydata.org/docs/reference/api/pandas.Series.argmax.html

我的实现是返回最大的index

**Comment by Menooker** [comment]
https://github.com/Menooker/KunQuant/pull/20 能否看一下测试这个PR是不是能解决问题？

**Comment by wangzaimilk123** [comment]
感谢老哥的修改，我看了下Commits主要是改了Ops.hpp，我去修改了这个文件删除build文件夹重新build后还是对不上，不知道是哪里有问题欸，然后我看了48只股票5分钟数据的话，这个框架和qlib生成的相减，一是这个IMAX IMIN有问题，另外就是WVMA好像有20多个数据点差的特别多(正负一的范围)，这个我还在排查原因

**Comment by Menooker** [comment]
我想问下一开始你说的0.6968635916291558的那个数值的问题还存在吗？

**Comment by Menooker** [comment]
> 另外就是WVMA好像有20多个数据点差的特别多(正负一的范围)，这个我还在排查原因

这个有可能是数值求值顺序导致的精度问题。能否把出错位置附近的数据（close vol）发一下？并且发一下qlib和kun产生的结果呢？谢谢！

**Comment by Menooker** [comment]
> 若当前的high为0.6968635916291558，前五个bar的high为
> [ 0.6898481863442985, 0.6992020600574415, 0.6992020600574417, 0.6968635916291558, 0.6968635916291558 ]

对了这些数的max不应该是第三个吗？所以结果应该是0.6啊？

**Comment by Menooker** [comment]
> 若当前的high为0.6968635916291558，前五个bar的high为
> [ 0.6898481863442985, 0.6992020600574415, 0.6992020600574417, 0.6968635916291558, 0.6968635916291558 ]
> qlib计算的结果是0.8，但是本框架的计算结果是1，因为qlib是用第四个数据的index除5

对了，你给的这个数据里面，min和max分别是0.6898481863442985 0.6992020600574417，和当前的high 0.6968635916291558无关，qlib结果应该是0.2吧？

**Comment by Menooker** [comment]
在PR里面，我加了一个新的测试：
```python
def test_argmin_issue19():
    #https://github.com/Menooker/KunQuant/issues/19
    modu = lib.getModule("test_argmin")
    assert(modu)
    inp = np.empty((6, 8),"float32")
    data = [ 0.6898481863442985, 0.6992020600574415, 0.6992020600574417, 0.6968635916291558, 0.6968635916291558, 0.6968635916291558 ]
    for i in range(6):
        inp[i, :] = data[i]
    executor = kr.createSingleThreadExecutor()
    out = kr.runGraph(executor, modu, {"a": inp}, 0, 6)
    expected = pd.DataFrame(inp).rolling(5, min_periods=1).apply(lambda x: x.argmin() + 1, raw=True)
    output = out["ou2"][4:]
    np.testing.assert_allclose(output, expected[4:], rtol=1e-6, equal_nan=True)
```

结果是一致的

**Comment by Menooker** [comment]
我更新了fix_IMAX 分支，你可以再切换到这个分支试试看。这次更新了循环顺序，这样应该更贴近正常的求值顺序，也有可能可以帮助解决IMAX 和WVMA的问题。如果还不行的话，可以试试看修改`generate.py`. 在projects/Alpha158/generate.py （如果你用的是目前默认的Alpha158的话）。

`src = compileit(f, "alpha158", dtype='double', partition_factor=4, output_layout="TS", input_layout="TS", options={"opt_reduce": True, "fast_log": True})`

这一行中`"opt_reduce":True`的True改成False。这样会关闭有关ReduceSum的优化，可能有助于解决数值精度问题。

**Comment by wangzaimilk123** [comment]
谢谢您，我这边用最新的代码以后问题解决了，同时我发现了一个数值问题，因为我的normalize方法，导致我的价格小数位数在15位，qlib应该是保留八位有效数字

**Comment by Menooker** [comment]
> 谢谢您，我这边用最新的代码以后问题解决了

我确认一下，所以`fix_IMAX`这个分支的改动可以解决你的问题是嘛？如果是的话，那我这边可以合并那个分支了。

> 同时我发现了一个数值问题，因为我的normalize方法，导致我的价格小数位数在15位，qlib应该是保留八位有效数字

这个问题需要KunQuant这边有啥改动吗？还是测试本身的问题？

**Comment by wangzaimilk123** [comment]
可以解决现在的问题
不用有改动，是qlib的datatype问题
谢谢您





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Menooker/KunQuant] Alpha158分钟线因子计算中IMAX IMIN计算问题 (Issue #19)














  
谢谢您，我这边用最新的代码以后问题解决了
  
我确认一下，所以fix_IMAX这个分支的改动可以解决你的问题是嘛？如果是的话，那我这边可以合并那个分支了。
  
同时我发现了一个数值问题，因为我的normalize方法，导致我的价格小数位数在15位，qlib应该是保留八位有效数字
  
这个问题需要KunQuant这边有啥改动吗？还是测试本身的问题？
