### ISSUE TITLE
打包迁移问题

### ISSUE THREAD

**Issue by muhoushaonian** [Menooker/KunQuant#22]
请问如果从一台ubuntu环境迁移到另外一台环境的话，还需要重新cmake和build吗

**Comment by Menooker** [comment]
如果系统环境一致（glibc，python版本），而且CPU 指令集和你cmake时候通过`-DKUN_AVX512*`启用的指令集一致，你可以直接把`libKunRuntime.so` `KunRunner.cpython-???-x86_64-linux-gnu.so` 还有因子的so拷贝到新的机器。通过指定PYTHONPATH之后用python import。如果遇到报错找不到libKunRuntime.so的情况，通过LD_LIBRARY_PATH指定一下libKunRuntime.so的文件夹路径即可。如果环境、硬件不一致，你可以先尝试拷贝试一下，如果不行那么需要重新cmake 重新build。

**Comment by Menooker** [comment]
有关这个问题还有其他疑问吗？

**Comment by muhoushaonian** [comment]
没有了，谢谢哥，我来关掉这个issue
