### ISSUE TITLE
框架计算问题探讨

### ISSUE THREAD

**Issue by muhoushaonian** [Menooker/KunQuant#26]
哥你好，我在计算TRIX的指标的时候，发现pmtr = ExpMovingAvg(ExpMovingAvg(ExpMovingAvg(BackRef(self.close, 1), n), n), n)这一项输出会为NaN，请问是为什么呢

**Comment by Menooker** [comment]
和moving average一样，EMA时间长度为N时，最早的N个输出都会是nan。嵌套M层EMA之后前面输出会有M*N个nan

前两天通过邮件回复了，貌似github收不到啊。。。

**Comment by muhoushaonian** [comment]
明白了明白了谢谢哥（周末去爬山没刷github

**Comment by muhoushaonian** [comment]
欸哥我看了下，如果是ExpMovingAvg(ExpMovingAvg(ExpMovingAvg(self.close, n), n), n)没问题，但是如果是ExpMovingAvg(ExpMovingAvg(ExpMovingAvg(BackRef(self.close, 1), n), n), n)这样的话所有的输出都是NaN，这样应该是有问题，是BackRef不能和EMA和MA这种算子嵌套用吗

**Comment by Menooker** [comment]
是EMA实现的bug，在#28 修正了。现在的行为和pandas的v.ewm(span=5, adjust=False, ignore_na=True).mean() 一致
