### ISSUE TITLE
C Api中如何区分参数含义

### ISSUE THREAD

**Issue by SniperUsopp** [Menooker/KunQuant#6]
非常感谢作者开发CAPI，我已经成功使用RUST接入了KunQuant。
我在使用CAPI时，发现一些问题。目前的CApi中，输入参数及输出参数都是float*类型，那么在进行计算时，如何区分输入参数具体是哪个量价指标呢？
我看在Python版本的API中，runGraph函数接受的输入及输出参数都是支持dict类型，这样能保留参数的信息，而在CAPI中，似乎没有办法传入参数的含义信息。

**Comment by Menooker** [comment]
可以看一下capi例子中

    KunBufferNameMapHandle bufs = kunCreateBufferNameMap();
    kunSetBufferNameMap(bufs, "input", inputs);
    kunSetBufferNameMap(bufs, "output", outputs);


引号中”input”即输入的字段名。这个例子里面由于只有一个输入字段，所以用了“input”作为名字。实际因子库中“input”应该改为“close” “open”等实际因子的输入字段名。具体因子用了哪些字段，需要看因子定义了哪些Input对象，可以看一下自定义因子的文档。

对于每个不同的字段，需要各调用一次kunSetBufferNameMap。BufferNameMap的作用和python api的dict作用是一致的。例如：

kunSetBufferNameMap(bufs, "open", ptrOpen);
kunSetBufferNameMap(bufs, "high", ptrHigh);

输出buffer也是通过同一个BufferNameMap对象来传递

**Comment by SniperUsopp** [comment]
理解了， 非常感谢。那对于三维数据该如何处理呢？通常在计算因子时，可能还有一个股票种类的维度。比如我想分别传入apple的open和google的open价格。请问对于这种情况有什么建议的做法嚒。

**Comment by Menooker** [comment]
> 理解了， 非常感谢。那对于三维数据该如何处理呢？通常在计算因子时，可能还有一个股票种类的维度。比如我想分别传入apple的open和google的open价格。请问对于这种情况有什么建议的做法嚒。

可以看一下项目Readme，里面的例子就是多只股票同时作为输入的

```
# we need a multiple of 8 number of stocks
watch_list = ["000002", "000063", ...]
```

注意输入的`float*` buffer需要内存分布为ST8s，也就是例如"close",原来是`[stocks, time]` 的2D矩阵，需要重组为 ` [stocks//8, time, 8]`。具体如何完成这个转置，可以参考Python（Readme里）和C （CAPI文档）的实现

**Comment by SniperUsopp** [comment]
明白了，非常感谢，我去试试。没有其他问题了
