### ISSUE TITLE
请问KunQuant是否支持流式计算

### ISSUE THREAD

**Issue by SniperUsopp** [Menooker/KunQuant#7]
通常在计算因子时，有很多因子是根据实时的信号一直在流式计算的。即输入参数不是将整个时间窗口的输入，而是每次仅输入当前时间切面的数据，请问KunQuant是否支持这种流式计算的能力。

**Comment by Menooker** [comment]
目前只支持批处理模式。对于实时处理这方面我接触不多，不知道你需要什么样的流处理接口呢？

例如每个时间点用户输入所有标的的整个横截面数据，然后突出所有标的的因子结果？

**Comment by SniperUsopp** [comment]
对的，是这个意思。因为在实盘情况中，数据是按时间点一次输入的。KunQuant是否支持，输入所有标的整个时间点的截面数据。然后返回各因子的在这个时间点的值。 因为有些因子时需要用历史数据计算的，所以这样可能会需要存储一些状态信息

**Comment by Menooker** [comment]
这个暂时还没有支持。请问你需要比较高频和低延时的实现吗？否则我基于现有代码可以改出一个流式计算的版本，但是如果要低延时的话，估计要较大的重构

**Comment by SniperUsopp** [comment]
我想应该不需要非常的低延迟

**Comment by SniperUsopp** [comment]
非常感谢支持！！太给力了，希望开通捐赠渠道

**Comment by Menooker** [comment]
哈哈😄这个功能做出来可能还需要一段时间哈

在 2024年3月20日，00:19，JunJi ***@***.***> 写道：

﻿

非常感谢支持！！太给力了，希望开通捐赠渠道

**Comment by Menooker** [comment]
相关功能在 https://github.com/Menooker/KunQuant/pull/8 开发中

**Comment by Menooker** [comment]
> 非常感谢支持！！太给力了，希望开通捐赠渠道

老哥如果愿意可以去知乎https://zhuanlan.zhihu.com/p/682114254 赞赏 :)

**Comment by Menooker** [comment]
#8 已合并。 文档可以参考https://github.com/Menooker/KunQuant/blob/main/Stream.md
